file_length:
  - 800
function_body_length:
  - 100
excluded:
  - .build
  - External
  - Sources/libgonzales/Sampler/SobolMatrices.swift
opt_in_rules:
  - unused_parameter
disabled_rules:
  - function_parameter_count
  - opening_brace
  - cyclomatic_complexity
  - large_tuple
  - trailing_comma
identifier_name:
  excluded:
    - x
    - y
    - z
    - s
    - t
  min_length: 3
  max_length: 40
