file_length:
  - 800
function_body_length:
  - 100
excluded:
  - .build
  - External
  - Sources/libgonzales/Sampler/SobolMatrices.swift
opt_in_rules:
  - unused_parameter
identifier_name:
  excluded:
    - x
    - y
    - z
    - s
    - t
    - i
    - k
    - m
    - f
    - a
    - b
    - j
    - r
    - c
    - d
    - v
    - n
    - p
    - h
    - o
    - l
    - u
    - g
    - e
    - w
    - q
    - to
    - uv
disabled_rules:
  - force_cast
  - function_parameter_count
  - opening_brace
  - cyclomatic_complexity
  - large_tuple
  - trailing_comma
