opt_in_rules:
  - unused_parameter
identifier_name:
  excluded:
    - x
    - y
    - z
    - s
    - t
    - i
    - k
    - m
    - f
    - a
    - b
    - j
    - r
    - c
    - d
    - v
    - n
    - p
    - h
    - o
    - l
    - u
    - g
    - e
    - w
    - q
