# Real Jakob & Hanika 2019 spectral upsampling ("A Low-Dimensional Function
# Space for Efficient Spectral Upsampling") — the actual method PBRT uses,
# ported from pbrt-v4's src/pbrt/cmd/rgb2spec_opt.cpp (the offline table
# generator) and src/pbrt/util/color.h/.cpp (RGBSigmoidPolynomial).
#
# Same architecture PBRT ships: a res x res x res x 3(planes) coefficient
# table is generated ONCE, OFFLINE (build_spectrum_table, res=64, ~71s on
# this machine, warm-start continuation same as pbrt's generator), and
# committed as a data asset (src/gonzales/data/rgb2spectrum_table.bin,
# generated by /tmp .../table_verify.mojo-style driver — see
# save_spectrum_table). At render/scene-load time gonzales only ever calls
# load_spectrum_table + rgb_to_coeffs_table_lookup — an O(1) trilinear
# lookup, matching pbrt's RGBToSpectrumTable::operator(). No optimizer runs
# during a normal render, same as pbrt. Verified against direct per-color
# gauss_newton_solve: sub-1%-relative-error recovery at res=64 for every
# tested color (white/grey/saturated-RGB/cornell-wall/near-black).
#
# gauss_newton_solve (on-demand, starts from coeffs=(0,0,0)) is kept as a
# standalone entry point — it's what build_spectrum_table itself is built
# from (via the shared _gauss_newton_core), and remains useful for one-off
# solves or regenerating the table at a different resolution.
#
# A spectrum here is s(lambda) = sigmoid(c0*lambda^2 + c1*lambda + c2) for a
# wavelength lambda in actual nanometers — always in (0,1) by construction
# (sigmoid is bounded), so it's always a physically valid reflectance, no
# clamping ever needed (unlike the layer-1 basis-function approximation in
# spectrum.mojo). Wiring this table into the actual light-transport code
# (replacing spectrum.mojo's RGB<->spectral conversion) is separate,
# not-yet-done follow-up work.

from std.math import sqrt, exp, sin, asin
from std.memory import alloc

comptime CIE_LAMBDA_MIN = Float64(360.0)
comptime CIE_LAMBDA_MAX = Float64(830.0)
comptime CIE_SAMPLES = 95
comptime CIE_FINE_SAMPLES = (CIE_SAMPLES - 1) * 3 + 1  # 283
comptime RGB2SPEC_EPSILON = Float64(1e-4)

# ── CIE 1931 2-degree standard observer, 5nm steps, 360-830nm (95 samples) ──
# Verbatim from pbrt-v4's rgb2spec_opt.cpp.

def _CIE_X() -> List[Float64]:
    return [
        0.000129900000, 0.000232100000, 0.000414900000, 0.000741600000, 0.001368000000,
        0.002236000000, 0.004243000000, 0.007650000000, 0.014310000000, 0.023190000000,
        0.043510000000, 0.077630000000, 0.134380000000, 0.214770000000, 0.283900000000,
        0.328500000000, 0.348280000000, 0.348060000000, 0.336200000000, 0.318700000000,
        0.290800000000, 0.251100000000, 0.195360000000, 0.142100000000, 0.095640000000,
        0.057950010000, 0.032010000000, 0.014700000000, 0.004900000000, 0.002400000000,
        0.009300000000, 0.029100000000, 0.063270000000, 0.109600000000, 0.165500000000,
        0.225749900000, 0.290400000000, 0.359700000000, 0.433449900000, 0.512050100000,
        0.594500000000, 0.678400000000, 0.762100000000, 0.842500000000, 0.916300000000,
        0.978600000000, 1.026300000000, 1.056700000000, 1.062200000000, 1.045600000000,
        1.002600000000, 0.938400000000, 0.854449900000, 0.751400000000, 0.642400000000,
        0.541900000000, 0.447900000000, 0.360800000000, 0.283500000000, 0.218700000000,
        0.164900000000, 0.121200000000, 0.087400000000, 0.063600000000, 0.046770000000,
        0.032900000000, 0.022700000000, 0.015840000000, 0.011359160000, 0.008110916000,
        0.005790346000, 0.004109457000, 0.002899327000, 0.002049190000, 0.001439971000,
        0.000999949300, 0.000690078600, 0.000476021300, 0.000332301100, 0.000234826100,
        0.000166150500, 0.000117413000, 0.000083075270, 0.000058706520, 0.000041509940,
        0.000029353260, 0.000020673830, 0.000014559770, 0.000010253980, 0.000007221456,
        0.000005085868, 0.000003581652, 0.000002522525, 0.000001776509, 0.000001251141,
    ]

def _CIE_Y() -> List[Float64]:
    return [
        0.000003917000, 0.000006965000, 0.000012390000, 0.000022020000, 0.000039000000,
        0.000064000000, 0.000120000000, 0.000217000000, 0.000396000000, 0.000640000000,
        0.001210000000, 0.002180000000, 0.004000000000, 0.007300000000, 0.011600000000,
        0.016840000000, 0.023000000000, 0.029800000000, 0.038000000000, 0.048000000000,
        0.060000000000, 0.073900000000, 0.090980000000, 0.112600000000, 0.139020000000,
        0.169300000000, 0.208020000000, 0.258600000000, 0.323000000000, 0.407300000000,
        0.503000000000, 0.608200000000, 0.710000000000, 0.793200000000, 0.862000000000,
        0.914850100000, 0.954000000000, 0.980300000000, 0.994950100000, 1.000000000000,
        0.995000000000, 0.978600000000, 0.952000000000, 0.915400000000, 0.870000000000,
        0.816300000000, 0.757000000000, 0.694900000000, 0.631000000000, 0.566800000000,
        0.503000000000, 0.441200000000, 0.381000000000, 0.321000000000, 0.265000000000,
        0.217000000000, 0.175000000000, 0.138200000000, 0.107000000000, 0.081600000000,
        0.061000000000, 0.044580000000, 0.032000000000, 0.023200000000, 0.017000000000,
        0.011920000000, 0.008210000000, 0.005723000000, 0.004102000000, 0.002929000000,
        0.002091000000, 0.001484000000, 0.001047000000, 0.000740000000, 0.000520000000,
        0.000361100000, 0.000249200000, 0.000171900000, 0.000120000000, 0.000084800000,
        0.000060000000, 0.000042400000, 0.000030000000, 0.000021200000, 0.000014990000,
        0.000010600000, 0.000007465700, 0.000005257800, 0.000003702900, 0.000002607800,
        0.000001836600, 0.000001293400, 0.000000910930, 0.000000641530, 0.000000451810,
    ]

def _CIE_Z() -> List[Float64]:
    return [
        0.000606100000, 0.001086000000, 0.001946000000, 0.003486000000, 0.006450001000,
        0.010549990000, 0.020050010000, 0.036210000000, 0.067850010000, 0.110200000000,
        0.207400000000, 0.371300000000, 0.645600000000, 1.039050100000, 1.385600000000,
        1.622960000000, 1.747060000000, 1.782600000000, 1.772110000000, 1.744100000000,
        1.669200000000, 1.528100000000, 1.287640000000, 1.041900000000, 0.812950100000,
        0.616200000000, 0.465180000000, 0.353300000000, 0.272000000000, 0.212300000000,
        0.158200000000, 0.111700000000, 0.078249990000, 0.057250010000, 0.042160000000,
        0.029840000000, 0.020300000000, 0.013400000000, 0.008749999000, 0.005749999000,
        0.003900000000, 0.002749999000, 0.002100000000, 0.001800000000, 0.001650001000,
        0.001400000000, 0.001100000000, 0.001000000000, 0.000800000000, 0.000600000000,
        0.000340000000, 0.000240000000, 0.000190000000, 0.000100000000, 0.000049999990,
        0.000030000000, 0.000020000000, 0.000010000000, 0.000000000000, 0.000000000000,
        0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000,
        0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000,
        0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000,
        0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000,
        0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000,
        0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000,
        0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000, 0.000000000000,
    ]

# CIE D65 illuminant, 5nm, 360-830nm, normalized to unit luminance
# (divided by 10566.864005283874576, matching pbrt's N(x) macro exactly).
def _CIE_D65_RAW() -> List[Float64]:
    return [
        46.6383, 49.3637, 52.0891, 51.0323, 49.9755, 52.3118, 54.6482,
        68.7015, 82.7549, 87.1204, 91.486, 92.4589, 93.4318, 90.057,
        86.6823, 95.7736, 104.865, 110.936, 117.008, 117.41, 117.812,
        116.336, 114.861, 115.392, 115.923, 112.367, 108.811, 109.082,
        109.354, 108.578, 107.802, 106.296, 104.79, 106.239, 107.689,
        106.047, 104.405, 104.225, 104.046, 102.023, 100.0, 98.1671,
        96.3342, 96.0611, 95.788, 92.2368, 88.6856, 89.3459, 90.0062,
        89.8026, 89.5991, 88.6489, 87.6987, 85.4936, 83.2886, 83.4939,
        83.6992, 81.863, 80.0268, 80.1207, 80.2146, 81.2462, 82.2778,
        80.281, 78.2842, 74.0027, 69.7213, 70.6652, 71.6091, 72.979,
        74.349, 67.9765, 61.604, 65.7448, 69.8856, 72.4863, 75.087,
        69.3398, 63.5927, 55.0054, 46.4182, 56.6118, 66.8054, 65.0941,
        63.3828, 63.8434, 64.304, 61.8779, 59.4519, 55.7054, 51.959,
        54.6998, 57.4406, 58.8765, 60.3125,
    ]
comptime _CIE_D65_NORM = Float64(10566.864005283874576)

# sRGB <-> XYZ matrices (row-major), from pbrt-v4's rgb2spec_opt.cpp.
comptime _XYZ_TO_SRGB00 = Float64(3.240479); comptime _XYZ_TO_SRGB01 = Float64(-1.537150); comptime _XYZ_TO_SRGB02 = Float64(-0.498535)
comptime _XYZ_TO_SRGB10 = Float64(-0.969256); comptime _XYZ_TO_SRGB11 = Float64(1.875991); comptime _XYZ_TO_SRGB12 = Float64(0.041556)
comptime _XYZ_TO_SRGB20 = Float64(0.055648); comptime _XYZ_TO_SRGB21 = Float64(-0.204043); comptime _XYZ_TO_SRGB22 = Float64(1.057311)

def _cie_interp(table: List[Float64], lambda_nm: Float64) -> Float64:
    """One-time-setup variant (build_quadrature_tables/_cie_d65 below, both
    called only during table generation or the on-demand solver, never per
    render-sample) — takes an owned List directly. Render-hot-path callers
    must use _cie_interp_ptr instead, on a table built ONCE and threaded as
    a pointer (see SpectralHandle in spectrum.mojo) — re-deriving these
    tables per call (as this function's List-returning data sources like
    _CIE_D65_RAW() would require) means rebuilding a 95-element list from
    scratch on every single wavelength evaluation, which is fine for a
    handful of one-time-setup calls but not for a hot path."""
    var x = lambda_nm - CIE_LAMBDA_MIN
    x *= Float64(CIE_SAMPLES - 1) / (CIE_LAMBDA_MAX - CIE_LAMBDA_MIN)
    var offset = Int(x)
    if offset < 0:
        offset = 0
    if offset > CIE_SAMPLES - 2:
        offset = CIE_SAMPLES - 2
    var weight = x - Float64(offset)
    return (Float64(1.0) - weight) * table[offset] + weight * table[offset + 1]

@always_inline
def _cie_interp_ptr(table: UnsafePointer[Float64, MutAnyOrigin], lambda_nm: Float64) -> Float64:
    """Render-hot-path variant of _cie_interp — takes a raw pointer into a
    table built ONCE (see SpectralHandle in spectrum.mojo), so calling this
    every wavelength/every NEE sample costs nothing beyond the interpolation
    itself (no per-call allocation)."""
    var x = lambda_nm - CIE_LAMBDA_MIN
    x *= Float64(CIE_SAMPLES - 1) / (CIE_LAMBDA_MAX - CIE_LAMBDA_MIN)
    var offset = Int(x)
    if offset < 0:
        offset = 0
    if offset > CIE_SAMPLES - 2:
        offset = CIE_SAMPLES - 2
    var weight = x - Float64(offset)
    return (Float64(1.0) - weight) * table[offset] + weight * table[offset + 1]

def _cie_d65(lambda_nm: Float64) -> Float64:
    """One-time-setup only (see _cie_interp's docstring) — rebuilds the
    95-element D65 list every call, acceptable only for the ~283-sample
    build_quadrature_tables pass, never for a render hot path."""
    return _cie_interp(_CIE_D65_RAW(), lambda_nm) / _CIE_D65_NORM

# ── Fine composite-quadrature tables (Simpson's 3/8 rule), built once ───────

@fieldwise_init
struct _QuadratureTables(Copyable, Movable):
    var lambda_tbl: List[Float64]        # CIE_FINE_SAMPLES wavelengths (nm)
    var rgb_tbl0: List[Float64]          # per-sample R response (xyz_to_srgb . xyz(lambda) . D65(lambda) . weight)
    var rgb_tbl1: List[Float64]
    var rgb_tbl2: List[Float64]
    var xyz_white0: Float64
    var xyz_white1: Float64
    var xyz_white2: Float64

def build_quadrature_tables() -> _QuadratureTables:
    var h = (CIE_LAMBDA_MAX - CIE_LAMBDA_MIN) / Float64(CIE_FINE_SAMPLES - 1)
    var lambda_tbl = List[Float64](capacity=CIE_FINE_SAMPLES)
    var rgb_tbl0 = List[Float64](capacity=CIE_FINE_SAMPLES)
    var rgb_tbl1 = List[Float64](capacity=CIE_FINE_SAMPLES)
    var rgb_tbl2 = List[Float64](capacity=CIE_FINE_SAMPLES)
    for _ in range(CIE_FINE_SAMPLES):
        lambda_tbl.append(Float64(0.0)); rgb_tbl0.append(Float64(0.0))
        rgb_tbl1.append(Float64(0.0)); rgb_tbl2.append(Float64(0.0))
    var xw0 = Float64(0.0); var xw1 = Float64(0.0); var xw2 = Float64(0.0)

    var cie_x_tbl = _CIE_X(); var cie_y_tbl = _CIE_Y(); var cie_z_tbl = _CIE_Z()

    for i in range(CIE_FINE_SAMPLES):
        var lam = CIE_LAMBDA_MIN + Float64(i) * h
        var xv = _cie_interp(cie_x_tbl, lam)
        var yv = _cie_interp(cie_y_tbl, lam)
        var zv = _cie_interp(cie_z_tbl, lam)
        var illum = _cie_d65(lam)

        var weight = Float64(3.0) / Float64(8.0) * h
        if i == 0 or i == CIE_FINE_SAMPLES - 1:
            pass
        elif (i - 1) % 3 == 2:
            weight *= Float64(2.0)
        else:
            weight *= Float64(3.0)

        lambda_tbl[i] = lam
        var xyz0 = xv; var xyz1 = yv; var xyz2 = zv
        rgb_tbl0[i] = (_XYZ_TO_SRGB00*xyz0 + _XYZ_TO_SRGB01*xyz1 + _XYZ_TO_SRGB02*xyz2) * illum * weight
        rgb_tbl1[i] = (_XYZ_TO_SRGB10*xyz0 + _XYZ_TO_SRGB11*xyz1 + _XYZ_TO_SRGB12*xyz2) * illum * weight
        rgb_tbl2[i] = (_XYZ_TO_SRGB20*xyz0 + _XYZ_TO_SRGB21*xyz1 + _XYZ_TO_SRGB22*xyz2) * illum * weight

        xw0 += xyz0 * illum * weight
        xw1 += xyz1 * illum * weight
        xw2 += xyz2 * illum * weight

    return _QuadratureTables(lambda_tbl^, rgb_tbl0^, rgb_tbl1^, rgb_tbl2^, xw0, xw1, xw2)

# ── Sigmoid + CIELAB (perceptually-uniform residual metric, matches pbrt) ──

@always_inline
def _sigmoid(x: Float64) -> Float64:
    return Float64(0.5) * x / sqrt(Float64(1.0) + x * x) + Float64(0.5)

def _lab_f(t: Float64) -> Float64:
    comptime delta = Float64(6.0) / Float64(29.0)
    if t > delta * delta * delta:
        return t ** (Float64(1.0) / Float64(3.0))
    else:
        return t / (delta * delta * Float64(3.0)) + Float64(4.0) / Float64(29.0)

def _cie_lab(p0: Float64, p1: Float64, p2: Float64, tables: _QuadratureTables) -> Tuple[Float64, Float64, Float64]:
    # p is in the SAME "rgb_tbl"-weighted RGB space as eval_residual's `out` —
    # convert back through srgb_to_xyz first (matches pbrt's cie_lab, which
    # takes rgb_to_xyz @ p).
    comptime S00 = Float64(0.412453); comptime S01 = Float64(0.357580); comptime S02 = Float64(0.180423)
    comptime S10 = Float64(0.212671); comptime S11 = Float64(0.715160); comptime S12 = Float64(0.072169)
    comptime S20 = Float64(0.019334); comptime S21 = Float64(0.119193); comptime S22 = Float64(0.950227)
    var x = S00*p0 + S01*p1 + S02*p2
    var y = S10*p0 + S11*p1 + S12*p2
    var z = S20*p0 + S21*p1 + S22*p2
    var xw = tables.xyz_white0; var yw = tables.xyz_white1; var zw = tables.xyz_white2
    var l = Float64(116.0) * _lab_f(y / yw) - Float64(16.0)
    var a = Float64(500.0) * (_lab_f(x / xw) - _lab_f(y / yw))
    var b = Float64(200.0) * (_lab_f(y / yw) - _lab_f(z / zw))
    return (l, a, b)

def _eval_residual(c0: Float64, c1: Float64, c2: Float64, target_lab0: Float64, target_lab1: Float64, target_lab2: Float64, tables: _QuadratureTables) -> Tuple[Float64, Float64, Float64]:
    var out0 = Float64(0.0); var out1 = Float64(0.0); var out2 = Float64(0.0)
    for i in range(CIE_FINE_SAMPLES):
        var lam = (tables.lambda_tbl[i] - CIE_LAMBDA_MIN) / (CIE_LAMBDA_MAX - CIE_LAMBDA_MIN)
        var x = c0 * lam + c1
        x = x * lam + c2
        var s = _sigmoid(x)
        out0 += tables.rgb_tbl0[i] * s
        out1 += tables.rgb_tbl1[i] * s
        out2 += tables.rgb_tbl2[i] * s
    var (l, a, b) = _cie_lab(out0, out1, out2, tables)
    return (target_lab0 - l, target_lab1 - a, target_lab2 - b)

def _solve3x3(a00: Float64, a01: Float64, a02: Float64,
              a10: Float64, a11: Float64, a12: Float64,
              a20: Float64, a21: Float64, a22: Float64,
              b0: Float64, b1: Float64, b2: Float64) -> Tuple[Bool, Float64, Float64, Float64]:
    """Direct 3x3 linear solve via Cramer's rule (N is fixed at 3, no need
    for pbrt's generic LUP decomposition)."""
    var det = (a00*(a11*a22 - a12*a21) - a01*(a10*a22 - a12*a20) + a02*(a10*a21 - a11*a20))
    if abs(det) < Float64(1e-15):
        return (False, Float64(0.0), Float64(0.0), Float64(0.0))
    var inv_det = Float64(1.0) / det
    var x0 = (b0*(a11*a22 - a12*a21) - a01*(b1*a22 - a12*b2) + a02*(b1*a21 - a11*b2)) * inv_det
    var x1 = (a00*(b1*a22 - a12*b2) - b0*(a10*a22 - a12*a20) + a02*(a10*b2 - b1*a20)) * inv_det
    var x2 = (a00*(a11*b2 - b1*a21) - a01*(a10*b2 - b1*a20) + b0*(a10*a21 - a11*a20)) * inv_det
    return (True, x0, x1, x2)

@fieldwise_init
struct RGBSigmoidCoeffs(TrivialRegisterPassable):
    var c0: Float32
    var c1: Float32
    var c2: Float32

@always_inline
def eval_sigmoid_spectrum(coeffs: RGBSigmoidCoeffs, lambda_nm: Float32) -> Float32:
    """s(lambda) = sigmoid(c0*lambda^2 + c1*lambda + c2), lambda in actual nm
    (not normalized) — matches PBRT's RGBSigmoidPolynomial::operator()
    exactly, including its EvaluatePolynomial(lambda, c2, c1, c0) coefficient
    order (highest-degree coefficient last in the call, but c0 IS the
    quadratic term — see EvaluatePolynomial's Horner-scheme convention)."""
    var x = coeffs.c0 * lambda_nm + coeffs.c1
    x = x * lambda_nm + coeffs.c2
    var xf = Float64(x)
    return Float32(_sigmoid(xf))

def _gauss_newton_core(r: Float64, g: Float64, b: Float64, tables: _QuadratureTables, c0_init: Float64, c1_init: Float64, c2_init: Float64) -> Tuple[Float64, Float64, Float64]:
    """Direct port of pbrt's gauss_newton()/eval_residual()/eval_jacobian().
    Returns coefficients in NORMALIZED-wavelength space (the space the
    optimizer itself works in) — NOT yet transformed to raw-nm space, so
    these are the right values to hand back in as a warm-start initial guess
    for a neighboring grid point (see build_spectrum_table). Callers that
    want the final usable coefficients must pass the result through
    _coeffs_to_raw."""
    if r == g and g == b:
        var v = r
        if v <= Float64(0.0):
            return (Float64(0.0), Float64(0.0), Float64(-1e6))
        if v >= Float64(1.0):
            return (Float64(0.0), Float64(0.0), Float64(1e6))
        var c2c = (v - Float64(0.5)) / sqrt(v * (Float64(1.0) - v))
        return (Float64(0.0), Float64(0.0), c2c)

    var (tl, ta, tb) = _cie_lab(r, g, b, tables)

    var c0 = c0_init; var c1 = c1_init; var c2 = c2_init
    for _ in range(15):
        var (r0, r1, r2) = _eval_residual(c0, c1, c2, tl, ta, tb, tables)

        # Finite-difference Jacobian (central difference, matches pbrt).
        var jac = InlineArray[Float64, 9](fill=Float64(0.0))
        for k in range(3):
            var p0 = c0; var p1 = c1; var p2 = c2
            var m0 = c0; var m1 = c1; var m2 = c2
            if k == 0: p0 += RGB2SPEC_EPSILON; m0 -= RGB2SPEC_EPSILON
            elif k == 1: p1 += RGB2SPEC_EPSILON; m1 -= RGB2SPEC_EPSILON
            else: p2 += RGB2SPEC_EPSILON; m2 -= RGB2SPEC_EPSILON
            var (rp0, rp1, rp2) = _eval_residual(p0, p1, p2, tl, ta, tb, tables)
            var (rm0, rm1, rm2) = _eval_residual(m0, m1, m2, tl, ta, tb, tables)
            jac[0*3+k] = (rp0 - rm0) / (Float64(2.0) * RGB2SPEC_EPSILON)
            jac[1*3+k] = (rp1 - rm1) / (Float64(2.0) * RGB2SPEC_EPSILON)
            jac[2*3+k] = (rp2 - rm2) / (Float64(2.0) * RGB2SPEC_EPSILON)

        var (ok, dx0, dx1, dx2) = _solve3x3(
            jac[0], jac[1], jac[2],
            jac[3], jac[4], jac[5],
            jac[6], jac[7], jac[8],
            r0, r1, r2,
        )
        if not ok:
            break

        c0 -= dx0; c1 -= dx1; c2 -= dx2
        var resid_sq = r0*r0 + r1*r1 + r2*r2

        var cmax = c0
        if c1 > cmax: cmax = c1
        if c2 > cmax: cmax = c2
        if cmax > Float64(200.0):
            var scale = Float64(200.0) / cmax
            c0 *= scale; c1 *= scale; c2 *= scale

        if resid_sq < Float64(1e-6):
            break

    return (c0, c1, c2)

def _coeffs_to_raw(c0: Float64, c1: Float64, c2: Float64) -> RGBSigmoidCoeffs:
    """The Gauss-Newton fit is a polynomial in NORMALIZED wavelength space
    (lam=(lambda-360)/(830-360), see _eval_residual). eval_sigmoid_spectrum
    evaluates in RAW nm to match PBRT's RGBSigmoidPolynomial exactly, so
    re-express the fitted A*lam^2+B*lam+C via the substitution
    lam=(lambda-t0)*t1 as an equivalent quadratic in raw lambda — the same
    transform pbrt's rgb2spec_opt.cpp applies before writing its table
    (out[0]=A*t1^2, out[1]=B*t1-2*A*t0*t1^2, out[2]=C-B*t0*t1+A*(t0*t1)^2).
    A no-op for the achromatic case (A=B=0 there), so this is safe to apply
    unconditionally without a special case."""
    var t0 = CIE_LAMBDA_MIN
    var t1 = Float64(1.0) / (CIE_LAMBDA_MAX - CIE_LAMBDA_MIN)
    var a = c0; var bb = c1; var cc = c2
    var out_c0 = a * (t1 * t1)
    var out_c1 = bb * t1 - Float64(2.0) * a * t0 * (t1 * t1)
    var out_c2 = cc - bb * t0 * t1 + a * (t0 * t1) * (t0 * t1)
    return RGBSigmoidCoeffs(Float32(out_c0), Float32(out_c1), Float32(out_c2))

def gauss_newton_solve(r: Float64, g: Float64, b: Float64, tables: _QuadratureTables) -> RGBSigmoidCoeffs:
    """Real Jakob-Hanika optimization for one RGB value in [0,1]^3, starting
    from coeffs=(0,0,0) — the on-demand (no dense grid) entry point. Used
    directly for one-off conversions, and as the reference gauss_newton_
    core is used (with warm starts) by build_spectrum_table below."""
    var (c0, c1, c2) = _gauss_newton_core(r, g, b, tables, Float64(0.0), Float64(0.0), Float64(0.0))
    return _coeffs_to_raw(c0, c1, c2)

# ── Dense prebaked table (pbrt's actual shipped-asset approach) ────────────
#
# PBRT never runs gauss_newton_solve at render time. It generates a
# res x res x res x 3 (planes) grid ONCE OFFLINE (cmd/rgb2spec_opt.cpp's
# main()) and ships the result as compiled-in static data; at runtime
# RGBToSpectrumTable::operator() does an O(1) trilinear lookup. The
# functions below reproduce that same generator + lookup, so gonzales can
# ship the identical kind of asset instead of solving per-color at scene
# load. build_spectrum_table is meant to be run ONCE (via a standalone
# driver script) with its result saved via save_spectrum_table; normal
# renders only ever call load_spectrum_table + rgb_to_coeffs_table_lookup.

@always_inline
def _smoothstep(x: Float64) -> Float64:
    return x * x * (Float64(3.0) - Float64(2.0) * x)

@always_inline
def _inverse_smoothstep(x: Float64) -> Float64:
    """Analytic inverse of _smoothstep (solves 3x^2-2x^3=y for x), matching
    pbrt's InverseSmoothStep exactly."""
    var v = Float64(1.0) - Float64(2.0) * x
    if v > Float64(1.0): v = Float64(1.0)
    if v < Float64(-1.0): v = Float64(-1.0)
    return Float64(0.5) - sin(asin(v) / Float64(3.0))

def _table_rgb_for_grid_point(l: Int, z: Float64, x: Float64, y: Float64) -> Tuple[Float64, Float64, Float64]:
    """Places z (the max-channel value) and x,y (the other two channels'
    values, already expressed as fractions of z) into an (r,g,b) triple
    according to which channel l is the max — matches pbrt's rgb[l]=z,
    rgb[(l+1)%3]=x*z, rgb[(l+2)%3]=y*z assignment."""
    var rgb0: Float64; var rgb1: Float64; var rgb2: Float64
    var other1 = x * z
    var other2 = y * z
    if l == 0:
        rgb0 = z; rgb1 = other1; rgb2 = other2
    elif l == 1:
        rgb1 = z; rgb2 = other1; rgb0 = other2
    else:
        rgb2 = z; rgb0 = other1; rgb1 = other2
    return (rgb0, rgb1, rgb2)

def build_spectrum_table(res: Int) -> List[Float32]:
    """Direct port of pbrt's rgb2spec_opt.cpp main() grid-generation loop.
    Returns a flat array laid out as table[l][k][j][i][c] (c in 0..3), index
    = (((l*res + k)*res + j)*res + i)*3 + c, where l selects which channel
    (R=0/G=1/B=2) is the max, k indexes the max channel's warped value
    (0..res-1, see _smoothstep), and j,i index the other two channels'
    linear ratio-to-max (j -> channel (l+2)%3, i -> channel (l+1)%3).

    For each (l,j,i) column, walks k with warm-start continuation (each
    solve's result seeds the next k's initial guess) starting from k0=res/5
    outward in both directions — exactly pbrt's strategy, since a cold
    (0,0,0) start converges far more slowly near the gamut boundary (z near
    0 or 1, where the sigmoid saturates hardest)."""
    var tables = build_quadrature_tables()
    var total = 3 * res * res * res * 3
    var out = List[Float32](capacity=total)
    for _ in range(total):
        out.append(Float32(0.0))

    var k0 = res // 5
    if k0 >= res: k0 = res - 1

    for l in range(3):
        for j in range(res):
            var y = Float64(j) / Float64(res - 1)
            for i in range(res):
                var x = Float64(i) / Float64(res - 1)

                var zk0 = _smoothstep(_smoothstep(Float64(k0) / Float64(res - 1)))
                var (rgb0, rgb1, rgb2) = _table_rgb_for_grid_point(l, zk0, x, y)
                var (pc0, pc1, pc2) = _gauss_newton_core(rgb0, rgb1, rgb2, tables, Float64(0.0), Float64(0.0), Float64(0.0))
                var base = (((l * res + k0) * res + j) * res + i) * 3
                var coeffs0 = _coeffs_to_raw(pc0, pc1, pc2)
                out[base + 0] = coeffs0.c0; out[base + 1] = coeffs0.c1; out[base + 2] = coeffs0.c2

                var wc0 = pc0; var wc1 = pc1; var wc2 = pc2
                for k in range(k0 + 1, res):
                    var z = _smoothstep(_smoothstep(Float64(k) / Float64(res - 1)))
                    var (r2, g2, b2) = _table_rgb_for_grid_point(l, z, x, y)
                    var (nc0, nc1, nc2) = _gauss_newton_core(r2, g2, b2, tables, wc0, wc1, wc2)
                    var b_ = (((l * res + k) * res + j) * res + i) * 3
                    var coeffs = _coeffs_to_raw(nc0, nc1, nc2)
                    out[b_ + 0] = coeffs.c0; out[b_ + 1] = coeffs.c1; out[b_ + 2] = coeffs.c2
                    wc0 = nc0; wc1 = nc1; wc2 = nc2

                wc0 = pc0; wc1 = pc1; wc2 = pc2
                for k in range(k0 - 1, -1, -1):
                    var z = _smoothstep(_smoothstep(Float64(k) / Float64(res - 1)))
                    var (r2, g2, b2) = _table_rgb_for_grid_point(l, z, x, y)
                    var (nc0, nc1, nc2) = _gauss_newton_core(r2, g2, b2, tables, wc0, wc1, wc2)
                    var b_ = (((l * res + k) * res + j) * res + i) * 3
                    var coeffs = _coeffs_to_raw(nc0, nc1, nc2)
                    out[b_ + 0] = coeffs.c0; out[b_ + 1] = coeffs.c1; out[b_ + 2] = coeffs.c2
                    wc0 = nc0; wc1 = nc1; wc2 = nc2

    return out^

def rgb_to_coeffs_table_lookup(table: List[Float32], res: Int, r: Float64, g: Float64, b: Float64) -> RGBSigmoidCoeffs:
    """O(1) trilinear query against a table built by build_spectrum_table —
    the runtime counterpart of pbrt's RGBToSpectrumTable::operator(). r,g,b
    must be in [0,1] (callers with unbounded/illuminant RGB values should
    normalize by 2*max(r,g,b) first, matching PBRT's RGBUnboundedSpectrum/
    RGBIlluminantSpectrum convention, then rescale the evaluated spectrum by
    that same factor afterward)."""
    var maxc = 0
    var maxv = r
    if g >= maxv: maxc = 1; maxv = g
    if b >= maxv: maxc = 2; maxv = b

    if maxv <= Float64(0.0):
        return RGBSigmoidCoeffs(Float32(0.0), Float32(0.0), Float32(-1e6))

    var other1: Float64
    var other2: Float64
    if maxc == 0:
        other1 = g; other2 = b
    elif maxc == 1:
        other1 = b; other2 = r
    else:
        other1 = r; other2 = g

    var x = (other1 / maxv) * Float64(res - 1)
    var y = (other2 / maxv) * Float64(res - 1)
    var zf = maxv
    if zf > Float64(1.0): zf = Float64(1.0)
    var kf = _inverse_smoothstep(_inverse_smoothstep(zf)) * Float64(res - 1)

    var i0 = Int(x); var i1 = i0 + 1
    if i1 > res - 1: i1 = res - 1
    if i0 > res - 1: i0 = res - 1
    var ti = x - Float64(i0)

    var j0 = Int(y); var j1 = j0 + 1
    if j1 > res - 1: j1 = res - 1
    if j0 > res - 1: j0 = res - 1
    var tj = y - Float64(j0)

    var k0i = Int(kf); var k1i = k0i + 1
    if k1i > res - 1: k1i = res - 1
    if k0i > res - 1: k0i = res - 1
    var tk = kf - Float64(k0i)

    var acc0 = Float64(0.0); var acc1 = Float64(0.0); var acc2 = Float64(0.0)
    for corner in range(8):
        var ki = k0i if (corner & 1) == 0 else k1i
        var ji = j0 if (corner & 2) == 0 else j1
        var ii = i0 if (corner & 4) == 0 else i1
        var wk = (Float64(1.0) - tk) if (corner & 1) == 0 else tk
        var wj = (Float64(1.0) - tj) if (corner & 2) == 0 else tj
        var wi = (Float64(1.0) - ti) if (corner & 4) == 0 else ti
        var w = wk * wj * wi
        if w == Float64(0.0):
            continue
        var base = (((maxc * res + ki) * res + ji) * res + ii) * 3
        acc0 += w * Float64(table[base + 0])
        acc1 += w * Float64(table[base + 1])
        acc2 += w * Float64(table[base + 2])

    return RGBSigmoidCoeffs(Float32(acc0), Float32(acc1), Float32(acc2))

def save_spectrum_table(table: List[Float32], res: Int, path: String) raises:
    """Binary layout: 4-byte little-endian magic "SPTB", 4-byte res (Int32
    little-endian), then 3*res*res*res*3 Float32 values (native byte order,
    same order as build_spectrum_table's flat layout)."""
    var f = open(path, "w")
    var header = List[UInt8](capacity=8)
    header.append(UInt8(83)); header.append(UInt8(80)); header.append(UInt8(84)); header.append(UInt8(66))  # "SPTB"
    var res32 = Int32(res)
    var res_bytes = UnsafePointer(to=res32).bitcast[UInt8]()
    for i in range(4):
        header.append(res_bytes[i])
    f.write_bytes(Span(header))

    var count = len(table)
    var data = List[UInt8](capacity=count * 4)
    for i in range(count):
        var v = table[i]
        var vp = UnsafePointer(to=v).bitcast[UInt8]()
        data.append(vp[0]); data.append(vp[1]); data.append(vp[2]); data.append(vp[3])
    f.write_bytes(Span(data))
    f.close()

def load_spectrum_table(path: String) -> Tuple[Bool, Int, List[Float32]]:
    """Returns (ok, res, table). ok=False on any format mismatch/failure."""
    var empty = List[Float32]()
    try:
        var f = open(path, "r")
        var bytes = f.read_bytes()
        f.close()
        var n = len(bytes)
        if n < 8:
            return (False, 0, empty^)
        if bytes[0] != UInt8(83) or bytes[1] != UInt8(80) or bytes[2] != UInt8(84) or bytes[3] != UInt8(66):
            return (False, 0, empty^)
        var buf = alloc[UInt8](n)
        for i in range(n):
            buf[i] = bytes[i]
        var res = Int((buf + 4).bitcast[Int32]()[0])
        var expected_count = 3 * res * res * res * 3
        if n != 8 + expected_count * 4:
            buf.free()
            return (False, 0, empty^)
        var out = List[Float32](capacity=expected_count)
        for i in range(expected_count):
            out.append((buf + 8 + i * 4).bitcast[Float32]()[0])
        buf.free()
        return (True, res, out^)
    except:
        return (False, 0, empty^)

# ── Owning (load-once) table types ──────────────────────────────────────────
#
# CIE_Y_INTEGRAL, exact tabulated CIE X/Y/Z evaluation, and the D65
# illuminant convention all live here (not spectrum.mojo) since they're the
# same color-science data this file already ships (the 95-sample tabulated
# CIE curves, the D65 table, the XYZ<->sRGB matrices) — spectrum.mojo only
# adds wavelength SAMPLING and spectral-value arithmetic on top.
#
# IMPORTANT: SpectrumTable/CieXyzTables own List[...] buffers and are meant
# to be loaded/built EXACTLY ONCE per render (mirroring how gonzales already
# loads its sobol matrices once). Never embed these OWNING structs as a
# field in something reconstructed every bounce (e.g. shading.mojo's
# ShadeContext) — since List isn't ImplicitlyCopyable, that would force
# either a compile error or an expensive per-bounce deep copy of a
# multi-megabyte buffer. Render-hot-path code must instead go through
# spectrum.mojo's SpectralHandle (raw pointers extracted once from these
# owning structs, TrivialRegisterPassable, cheap to pass/reconstruct every
# bounce) and the pointer-based functions below (*_ptr / cie_d65_runtime /
# eval_illuminant_spectrum / rgb_illuminant_to_coeffs_ptr).

comptime CIE_Y_INTEGRAL = Float32(106.856895)

@fieldwise_init
struct SpectrumTable(Copyable, Movable):
    """A loaded dense Jakob-Hanika coefficient grid (see build_spectrum_table)
    ready for O(1) queries via rgb_to_coeffs_table_lookup."""
    var coeffs: List[Float32]
    var res: Int

def load_default_spectrum_table(path: String) -> Tuple[Bool, SpectrumTable]:
    var loaded = load_spectrum_table(path)
    var ok = loaded[0]
    var res = loaded[1]
    var table = loaded[2].copy()
    if not ok:
        return (False, SpectrumTable(List[Float32](), 0))
    return (True, SpectrumTable(table^, res))

@fieldwise_init
struct CieXyzTables(Copyable, Movable):
    """Exact tabulated CIE 1931 2-degree X/Y/Z color-matching functions
    (the same 95-sample data used to fit the spectrum table itself) PLUS the
    D65 illuminant table, all built once and reused for every spectral<->RGB
    conversion at render time. d65_tbl exists specifically so cie_d65_runtime
    never has to call the List-rebuilding _cie_d65/_CIE_D65_RAW() path — see
    that function's docstring."""
    var x_tbl: List[Float64]
    var y_tbl: List[Float64]
    var z_tbl: List[Float64]
    var d65_tbl: List[Float64]

def build_cie_xyz_tables() -> CieXyzTables:
    return CieXyzTables(_CIE_X(), _CIE_Y(), _CIE_Z(), _CIE_D65_RAW())

@always_inline
def xyz_to_srgb(x: Float64, y: Float64, z: Float64) -> Tuple[Float64, Float64, Float64]:
    var r = _XYZ_TO_SRGB00 * x + _XYZ_TO_SRGB01 * y + _XYZ_TO_SRGB02 * z
    var g = _XYZ_TO_SRGB10 * x + _XYZ_TO_SRGB11 * y + _XYZ_TO_SRGB12 * z
    var b = _XYZ_TO_SRGB20 * x + _XYZ_TO_SRGB21 * y + _XYZ_TO_SRGB22 * z
    return (r, g, b)

# ── Render-hot-path (pointer-based) API — no per-call allocation ───────────

@always_inline
def rgb_to_coeffs_table_lookup_ptr(table: UnsafePointer[Float32, MutAnyOrigin], res: Int, r: Float64, g: Float64, b: Float64) -> RGBSigmoidCoeffs:
    """Pointer-based twin of rgb_to_coeffs_table_lookup — identical trilinear
    query, just indexing a raw pointer (see SpectralHandle in spectrum.mojo)
    instead of an owned List, so it's safe to call every NEE sample without
    any per-call allocation or copy."""
    var maxc = 0
    var maxv = r
    if g >= maxv: maxc = 1; maxv = g
    if b >= maxv: maxc = 2; maxv = b

    if maxv <= Float64(0.0):
        return RGBSigmoidCoeffs(Float32(0.0), Float32(0.0), Float32(-1e6))

    var other1: Float64
    var other2: Float64
    if maxc == 0:
        other1 = g; other2 = b
    elif maxc == 1:
        other1 = b; other2 = r
    else:
        other1 = r; other2 = g

    var x = (other1 / maxv) * Float64(res - 1)
    var y = (other2 / maxv) * Float64(res - 1)
    var zf = maxv
    if zf > Float64(1.0): zf = Float64(1.0)
    var kf = _inverse_smoothstep(_inverse_smoothstep(zf)) * Float64(res - 1)

    var i0 = Int(x); var i1 = i0 + 1
    if i1 > res - 1: i1 = res - 1
    if i0 > res - 1: i0 = res - 1
    var ti = x - Float64(i0)

    var j0 = Int(y); var j1 = j0 + 1
    if j1 > res - 1: j1 = res - 1
    if j0 > res - 1: j0 = res - 1
    var tj = y - Float64(j0)

    var k0i = Int(kf); var k1i = k0i + 1
    if k1i > res - 1: k1i = res - 1
    if k0i > res - 1: k0i = res - 1
    var tk = kf - Float64(k0i)

    var acc0 = Float64(0.0); var acc1 = Float64(0.0); var acc2 = Float64(0.0)
    for corner in range(8):
        var ki = k0i if (corner & 1) == 0 else k1i
        var ji = j0 if (corner & 2) == 0 else j1
        var ii = i0 if (corner & 4) == 0 else i1
        var wk = (Float64(1.0) - tk) if (corner & 1) == 0 else tk
        var wj = (Float64(1.0) - tj) if (corner & 2) == 0 else tj
        var wi = (Float64(1.0) - ti) if (corner & 4) == 0 else ti
        var w = wk * wj * wi
        if w == Float64(0.0):
            continue
        var base = (((maxc * res + ki) * res + ji) * res + ii) * 3
        acc0 += w * Float64(table[base + 0])
        acc1 += w * Float64(table[base + 1])
        acc2 += w * Float64(table[base + 2])

    return RGBSigmoidCoeffs(Float32(acc0), Float32(acc1), Float32(acc2))

@always_inline
def cie_xyz_at_ptr(
    x_tbl: UnsafePointer[Float64, MutAnyOrigin],
    y_tbl: UnsafePointer[Float64, MutAnyOrigin],
    z_tbl: UnsafePointer[Float64, MutAnyOrigin],
    lambda_nm: Float64,
) -> Tuple[Float64, Float64, Float64]:
    return (
        _cie_interp_ptr(x_tbl, lambda_nm),
        _cie_interp_ptr(y_tbl, lambda_nm),
        _cie_interp_ptr(z_tbl, lambda_nm),
    )

@always_inline
def cie_d65_runtime(d65_tbl: UnsafePointer[Float64, MutAnyOrigin], lambda_nm: Float32) -> Float32:
    """PBRT's RUNTIME D65 illuminant (RGBColorSpace::illuminant): rescaled so
    integral(D65*ybar) = CIE_Y_integral (~106.86), NOT the unit-luminance
    convention used internally for FITTING the table. Pointer-based — see
    CieXyzTables.d65_tbl / SpectralHandle."""
    return Float32(_cie_interp_ptr(d65_tbl, Float64(lambda_nm)) / _CIE_D65_NORM) * CIE_Y_INTEGRAL

def rgb_illuminant_to_coeffs_ptr(table: UnsafePointer[Float32, MutAnyOrigin], res: Int, r: Float64, g: Float64, b: Float64) -> Tuple[RGBSigmoidCoeffs, Float64]:
    """PBRT's RGBIlluminantSpectrum convention for light-color RGB values
    (which are NOT in [0,1] like a reflectance): scale=2*max(r,g,b), fit the
    table against rgb/scale, evaluate as scale*rsp(lambda)*D65(lambda) — the
    fitted sigmoid tints the D65 shape, it doesn't stand alone. Returns the
    fitted coefficients plus the scale factor to apply via
    eval_illuminant_spectrum."""
    var maxc = r
    if g > maxc: maxc = g
    if b > maxc: maxc = b
    var scale = Float64(2.0) * maxc
    if scale < Float64(1e-6):
        scale = Float64(1.0)
    var coeffs = rgb_to_coeffs_table_lookup_ptr(table, res, r / scale, g / scale, b / scale)
    return (coeffs, scale)

@always_inline
def eval_illuminant_spectrum(coeffs: RGBSigmoidCoeffs, scale: Float64, d65_tbl: UnsafePointer[Float64, MutAnyOrigin], lambda_nm: Float32) -> Float32:
    return eval_sigmoid_spectrum(coeffs, lambda_nm) * Float32(scale) * cie_d65_runtime(d65_tbl, lambda_nm)
