name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest

    steps:
      - uses: actions/checkout@v3

      - name: Fix permissions
        run: |
          chown -R builder:builder .

      - name: Cache .build
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') || hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Check Versions
        run: |
          swift --version
          swiftlint --version

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Lint
        run: |
             SWIFT_LIB_PATH=$(find /usr -name libsourcekitdInProc.so | head -n 1 | xargs dirname)
             echo "Found Swift lib path: $SWIFT_LIB_PATH"
             export LD_LIBRARY_PATH=$SWIFT_LIB_PATH:$LD_LIBRARY_PATH
             swiftlint

      - name: Compile debug
        run: |
          mkdir -p .build
          make debug
