name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest

    steps:
      - uses: actions/checkout@v6

      - name: Fix permissions
        run: |
          chown -R builder:builder .

      - name: Cache .build
        uses: actions/cache@v5
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') || hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Run tests
        run: |
          uv sync
          SWIFT_LIB_PATH=$(find /usr -name libsourcekitdInProc.so | head -n 1 | xargs dirname)
          export LD_LIBRARY_PATH=$SWIFT_LIB_PATH:$LD_LIBRARY_PATH
          make testsuite SWIFT_TEST_OPTIONS="--jobs 2"
