name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/gonzales:latest

    steps:
      - uses: actions/checkout@v6

      - name: Fix permissions
        run: |
          chown -R builder:builder .

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Test
        run: |
          uv sync
          make test_release
